# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity: 
                class:  innobisBundle:Users
                property:   email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /
                check_path: /check
                username_parameter: _email
                password_parameter: _password
            logout:
                path: /logout
                target: / 
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    encoders:
        innobisBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12