<?php

namespace innobisBundle\Repository;

/**
 * ReclamosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamosRepository extends \Doctrine\ORM\EntityRepository
{
}
